Add the -z option to make tar.bz2 files, separate files for prof and debug.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -23,6 +23,7 @@ Option Value          Description
     -t                run the tests (optional, default=no, only works if -b is also specified )
     -v gitVersion     name of the git tag (required)
     -V                make this script verbose (optional, default = no )
+    -z                make the a tar.bz2 file(s) (optional, default = no )
     -h                print this help
 
 For additional details see: https://github.com/kutschke/KinKal_to_UPS
@@ -30,7 +31,7 @@ For additional details see: https://github.com/kutschke/KinKal_to_UPS
 }
 
 checkConfiguration(){
-  if [[ -z "$doBuild" && -z "$doInstall" && -z "$doClean" ]]; then
+  if [[ -z "$doBuild" && -z "$doInstall" && -z "$doClean" && -z "doTar" ]]; then
     echo "ERROR - no actions requested"
     return 1
   fi
@@ -76,7 +77,7 @@ processROOTQualifiers(){
        fi
      fi
   else
-     # If we are only cleaning then we do not need root
+     # If we are only cleaning or making tar files then we do not need root
      if [[ -n "$doBuild" && -n "$doInstall" ]]; then
        echo "Error - you must either supply the -r option or have an already setup version of ROOT in your shell."
        return 2
@@ -174,6 +175,30 @@ install() {
   return 0
 }
 
+makeTarFiles() {
+  echo "Begin making tar files."
+
+  setUPSVersion
+  echo "Version is: " $ups_style_version  "  " $ups_style_version
+
+  if [[ -d artexternals/KinKal/${ups_style_version} ]]; then
+    if [[ -n "$doProf" ]]; then
+      echo "Begin making tar file for prof version."
+      tar cjf KinKal_prof.tar.bz2 --exclude="*debug*" -C artexternals KinKal/${ups_style_version} KinKal/${ups_style_version}.version
+    fi
+
+    if [[ -n "$doDebug" ]]; then
+      echo "Begin making tar file for debug version."
+      tar cjf KinKal_debug.tar.bz2 --exclude="*prof*" -C artexternals KinKal/${ups_style_version} KinKal/${ups_style_version}.version
+    fi
+  else
+    echo "ERROR - could not find the ups product to tar: " artexternals/KinKal/${ups_style_version}
+    return 1
+  fi
+
+  return 0
+}
+
 # ********** main **********
 
 productName=KinKal
@@ -181,12 +206,15 @@ productName=KinKal
 # The directory that contains this script (and others that it will run).
 thisDir=`dirname $(readlink -f $0)`
 
+source ${thisDir}/funcs
+
 # Default values for command line argument options
 cmakever="v3_18_2"
 doClone=""
 doBuild=""
 doClean=""
 doInstall=""
+doTar=""
 doTest=""
 gitVersion=""
 nBuildThreads="1"
@@ -195,7 +223,7 @@ rootCmdLineOption=""
 verbose=""
 versionSuffix=""
 
-while getopts abCc:d:ij:nr:s:tv:Vh OPT; do
+while getopts abCc:d:ij:nr:s:tv:Vzh OPT; do
     case $OPT in
         b)
             doBuild=true
@@ -226,6 +254,9 @@ while getopts abCc:d:ij:nr:s:tv:Vh OPT; do
             ;;
         V)
             verbose="true"
+            ;;
+        z)
+            doTar="true"
             ;;
         h)
             usage
@@ -303,9 +334,15 @@ if [ -n "$doInstall" ]; then
   fi
 fi
 
+if [ -n "$doTar" ]; then
+  if ! makeTarFiles ; then
+    exit 7
+  fi
+fi
+
 if [ -n "$doClean" ]; then
   if ! clean ; then
-    exit 7
+    exit 8
   fi
 fi
 
