Lots of cleanup.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -2,33 +2,42 @@
 #
 # Master script to build and install KinKal.
 #
-#
-
 
 usage() {
 echo "
 
-Build, install and clean the KinKal ups product.
-The source directory and build directories will be created in the cwd.
+Build, test, install and cleanup the KinKal UPS product.
+The source directory and build directories will be created in the current working directory.
 
 usage: build <options>
 
-    -b build code
-    -C clean up working directories
-    -c VALUE cmake version and qualifiers
-    -i install as a product in $PRODUCTDIR/KinKal/$UPSVERSION
-    -j VALUE maximum number of build threads
-    -r VALUE root version and qualifiers
-    -t run the tests
-    -v GITVERSION ( name of the git tag )
-    -V make this script verbose
-    -x EXTRAQUALS the ups product qualifiers added
-    -d PRODUCTDIR
-    -h print this help
+Option Value      Description
+    -b            build code (optional, default = no )
+    -C            clean up working directories ( optional, default=no)
+    -c            VALUE cmake version and qualifiers (required if -b is selected )
+    -d PRODUCTS_INSTALL path to the root of the target UPS directory (required if -i selected)
+    -i            install as a UPS product ( optional, default=no)
+    -j VALUE      maximum number of build threads (optional, default =1)
+    -n            do a new clone; if absent expect on to be present (optional, default=no)
+    -r VALUE      root version and qualifiers (optional, if not specfied it will use UPS active)
+    -t            run the tests (optional, default=no, only works if -b is also specified )
+    -v GITVERSION name of the git tag (required)
+    -V            make this script verbose (optional, default = no )
+    -x EXTRAQUALS additional qualifiers to include in the name of the UPS product ( optional, default = "" )
+    -h            print this help
 
-The resulting ups product will have qualifiers that are those of the
-underlying ROOT product plus any additional qualifiers specfied by the
--x option.
+If the -i option is selected, the installed product will be installed in
+  ${PRODUCTS_INSTALL}/KinKal/${UPSVERSION}
+where UPSVERSION is determined automatically by the value of the -v option.
+For example, git version v0.1.1 becomes UPS version v00_01_01.
+
+The resulting UPS product will have qualifiers that are those of the underlying ROOT product
+plus any additional qualifiers specfied by the -x option.
+
+Notes:
+1) If the -n option is selected and there is already a directory named KinKal, the script will exit
+2) If the -b option is supplied it will overwrite any existing builds
+3) If the -i option is supplied it will overwrite any existing installs
 "
 }
 
@@ -39,7 +48,13 @@ checkConfiguration(){
   fi
 
   if [[ -n "$DOINSTALL" && -z "$GITVERSION" ]]; then
-    echo "You must supply a version when requesting an install."
+    echo "ERROR - you must supply a version when requesting an install."
+    return 2
+  fi
+
+  if [[ -n "$DOBUILD" && -z "$CMAKEVER" ]]; then
+    echo "ERROR - you must supply a cmake version when requesting a build."
+    return 3
   fi
 
   return 0
@@ -48,37 +63,40 @@ checkConfiguration(){
 
 # Fetch the code to be built.  If no version is specified, build the head.
 getCode() {
-  echo "
-
-  Begin clone and checkout for KinKal tag $GITVERSION
-
-"
-  git clone git@github.com:KFTrack/KinKal.git
-  if [[ "$?" != "0" ]]; then
-     return 1
-  fi
-  cd KinKal
-  if [[ -n "$GITVERSION" ]]; then
-    git checkout -b ${GITVERSION}_build_branch ${GITVERSION}
+  if [[ -n "${DOCLONE}" ]]; then
+    echo " Begin clone and checkout for KinKal tag "$GITVERSION
+    git clone git@github.com:KFTrack/KinKal.git
     if [[ "$?" != "0" ]]; then
-       return 2
+     return 1
     fi
-  fi
+    cd KinKal
+    if [[ -n "$GITVERSION" ]]; then
+      git checkout -b ${GITVERSION}_build_branch ${GITVERSION}
+      if [[ "$?" != "0" ]]; then
+         return 2
+      fi
+    fi
+    cd ..
+  else
+    echo "Using existing clone of KinKal: "
+  fi # End test on DOCLONE defined
 
   # Report the commit to be  built
-  git log -n 1 --decorate=full | cat  # Need the pipe cat or it will pipe to less
-  git status
+  if [[ -d KinKal ]]; then
+    cd KinKal
+    git log -n 1 --decorate=full | cat  # Need the pipe cat or it will pipe to less
+    git status
+    cd ..
+  else
+    echo "Error - The directory KinKal does not exist. "
+    return 3
+  fi
 
-  cd ..
   return 0
 }
 
 clean(){
-  echo "
-
-  Begin clean up.
-
-"
+  echo " Begin clean up. "
   for dir in KinKal build_prof build_debug; do
     if [[ -d ${dir} ]]; then
       echo "Removing " ${dir}
@@ -90,44 +108,47 @@ clean(){
 
 install() {
 
-  echo "
+  echo " Begin install. "
 
-   Begin install.
+  if [[ -d build_prof ]]; then
+    setup -B root ${ROOTBASEVER}
 
-"
-  export DEBUG_LEVEL=prof
-  export PACKAGE_VERSION=v00_01_01
-  export COMPILER_CODE=e20
-  export EXTRA_ROOT_QUALIFIERS=":p383b"
-  setup -B root ${ROOTBASEVER}
+    ${KINKAL_TO_UPS_DIR}/install
+    unsetup root
+  fi
 
-  ${KINKAL_TO_UPS_DIR}/install
+  if [[ -d build_debug ]]; then
+    setup -B root v6_20_08a -q+e20:+p383b:+debug
+
+    ${KINKAL_TO_UPS_DIR}/install
+    unsetup root
+  fi
 
   return 0
 }
 
 # ********** main **********
 
-echo "Start ... "
-
 PRODUCT=KinKal
 KINKAL_TO_UPS_DIR=`dirname $(readlink -f $0)`
 SOURCEDIR=`readlink -f $KINKAL_TO_UPS_DIR/..`
 
-
+DOCLONE=""
 DOBUILD=""
 DOCLEAN=""
-CMAKEVER=""
 DOINSTALL=""
-NBUILDTHREADS="1"
-PRODUCTDIR="$PWD"
+PRODUCTS_INSTALL="${PWD}/artexternals"
 ROOTBASEVER=""
-DOTEST=""
-VERBOSE="false"
-GITVERSION="foo"
+VERBOSE=""
 EXTRAQUALS=""
 
-while getopts bCc:d:ij:r:tv:Vxh OPT; do
+# Used by one or more of the subscripts build_one_verion, install, or installTableFile
+export CMAKEVER=""
+export GITVERSION=""
+export DOTEST=""
+export NBUILDTHREADS="1"
+
+while getopts abCc:d:ij:nr:tv:Vxh OPT; do
     case $OPT in
         b)
             export DOBUILD=true
@@ -137,23 +158,24 @@ while getopts bCc:d:ij:r:tv:Vxh OPT; do
         c)  export CMAKEVER=$OPTARG
             ;;
         d)
-            export PRODUCTDIR=$OPTARG
+            export PRODUCTS_INSTALL=$OPTARG
             ;;
         i)
             export DOINSTALL=true
-            echo "Processed install argument ..."
             ;;
         j)  export NBUILDTHREADS=$OPTARG
             ;;
+        n)  export DOCLONE=true
+            ;;
         r)  export ROOTBASEVER=$OPTARG
             ;;
-        t)  export DOTEST=true
+        t)  export DOTEST="true"
             ;;
         v)
             export GITVERSION=$OPTARG
             ;;
         V)
-            export VERBOSE=true
+            export VERBOSE="true"
             ;;
         x)
             export EXTRAQUALS=$OPTARG
@@ -164,27 +186,28 @@ while getopts bCc:d:ij:r:tv:Vxh OPT; do
             exit 0
             ;;
         *)
-            echo unknown option, exiting
+            echo "Error - unknown option, exiting"
 	    usage
             exit 1
             ;;
      esac
 done
 
-echo "Mark 1"
-
-echo "PRODUCT:       " ${PRODUCT}
-echo "KINKAL_TO_UPS_DIR:       " ${KINKAL_TO_UPS_DIR}
-echo "SOURCEDIR:     " ${SOURCEDIR}
-echo "DOBUILD:       " ${DOBUILD}
-echo "DOCLEAN:       " ${DOCLEAN}
-echo "CMAKEVER:      " ${CMAKEVER}
-echo "DOINSTALL:     " ${DOINSTALL}
-echo "PRODUCTDIR:    " ${PRODUCTDIR}
-echo "ROOTBASEVER:   " ${ROOTBASEVER}
-echo "DOTEST:        " ${DOTEST}
-echo "GITVERSION:    " ${GITVERSION}
-echo "NBUILDTHREADS: " ${NBUILDTHREADS}
+if [[ -n "$VERBOSE" ]]; then
+  echo "PRODUCT:           " ${PRODUCT}
+  echo "KINKAL_TO_UPS_DIR: " ${KINKAL_TO_UPS_DIR}
+  echo "SOURCEDIR:         " ${SOURCEDIR}
+  echo "DOCLONE:           " ${DOCLONE}
+  echo "DOBUILD:           " ${DOBUILD}
+  echo "DOCLEAN:           " ${DOCLEAN}
+  echo "CMAKEVER:          " ${CMAKEVER}
+  echo "DOINSTALL:         " ${DOINSTALL}
+  echo "PRODUCTS_INSTALL:  " ${PRODUCTS_INSTALL}
+  echo "ROOTBASEVER:       " ${ROOTBASEVER}
+  echo "DOTEST:            " ${DOTEST}
+  echo "GITVERSION:        " ${GITVERSION}
+  echo "NBUILDTHREADS:     " ${NBUILDTHREADS}
+fi
 
 if ! checkConfiguration ; then
   usage
@@ -221,5 +244,5 @@ if [ -n "$DOCLEAN" ]; then
   fi
 fi
 
-echo "KinKal_build completed with status 0"
+echo "KinKal_to_UPS/build completed with status 0"
 exit 0
diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,17 +1,84 @@
 #! /bin/bash
 #
-# Copy the files from the source and build areas to create a UPS product.
+# Copy files from the source and build areas to create a UPS product.
 #
 # This script unconditionally deletes previously existing installs of the
 # same product+version+qualifiers: use with care.
 #
+# The UPS qualifiers of the new product will be those of the version of
+# root on which it depends plus zero or more user specified additions.
+# The additions are provided as colon separated string.
+#
 
-PACKAGE_NAME=KinKal
+#
+# Convert the git tag into UPS version number style
+#    Examples: v0.1.1   to v00_01_01
+#              v0.100.1 to v00_100_01
+# Note: awk printf will expand field width to support numbers larger than 99.
+# Fixme: add more error checking and support other style tags, for example
+#        a suffix after the version number?
+setUPSVersion() {
+  nn=`echo $GITVERSION | awk 'BEGIN{FS="."} { print NF }'`
+  if [ "${nn}" != "3" ]; then
+     echo "Git version is not in a supported style: " ${GITVERSION}
+     return 1
+  fi
+  UPS_STYLE_VERSION=`echo $GITVERSION | sed 's/v//' | awk 'BEGIN{FS="."} { printf ( "v%02d_%02d_%02d\n", $1, $2, $3) }'`
+  return 0
+}
 
-# Check that the target UPS repo has been defined; if not provide a default.
-if [ "${PRODUCTS_INSTALL}" = '' ];then
-   PRODUCTS_INSTALL=${PWD}/artexternals
+# Extract the qualifiers for the version of root used to build this product.
+getRootQualifiers(){
+  export rootQuals=`echo $SETUP_ROOT | awk '{print $NF}'`
+  if [[ "$rootQuals" == "" ]]; then
+     echo "There are no root qualifiers ... "
+     return 1
+  fi
+  return 0
+}
+
+# Create the UPS qualifiers for the prof and debug versions
+#  - 3 versionS, needed for different places in UPSology
+#       - colon separated
+#       - dot separated
+#       - underscore separated
+setQualifiers(){
+  # Sort qualifiers by alphabetical order; xargs is used to strip trailing whitespace
+  export qualifiers_colons=`echo $rootQuals | sed 's/:/ /g' | tr " " "\n" | sort | tr "\n" " " | xargs | tr " " ":"`
+  export qualifiers_dots=`echo $qualifiers_colons | sed 's/:/./g'`
+  export qualifiers_underscores=`echo $qualifiers_colons | sed 's/:/_/g'`
+  return 0
+}
+
+#--- main ---
+
+setUPSVersion
+if [[ "$?" != 0 ]]; then
+    echo "Could not convert the git tag to a UPS version number. The git tag was: " ${GITVERSION}
+    exit 1
 fi
+echo "GITVER: " $UPS_STYLE_VERSION  $GITVERSION
+
+getRootQualifiers
+if [[ "$?" != 0 ]]; then
+    echo "getRootQualifiers failed: "
+    exit 1
+fi
+echo "Rootquals: " $rootQuals
+
+setQualifiers
+if [[ "$?" != 0 ]]; then
+    echo "setQualifiers failed: "
+    exit 1
+fi
+echo "prof:  " ${profQuals}
+echo "debug: " ${debugQuals}
+
+echo "quals(:)  " ${qualifiers_colons}
+echo "quals(.)  " ${qualifiers_dots}
+echo "quals(_)  " ${qualifiers_underscores}
+
+export PACKAGE_NAME=KinKal
 
 # Where to find the files in the installer package
 KINKAL_TO_UPS_DIR=`dirname $(readlink -f $0)`
@@ -31,26 +98,24 @@ if [ "${PACKAGE_SOURCE}" = '' ];then
 fi
 
 # There are two representations of operating system UPS flavor:
-# old style, for example: Linux64bit+2.6-2.12_e7
-# new style, for example: slf6.x86_64
+#   old style, for example: Linux64bit+2.6-2.12_e7
+#   new style, for example: slf6.x86_64
 # We need them both.
 old_flavour=`ups flavor -4`
 new_flavour=`get-directory-name subdir`
 
 # Build the names of the directories into which we will write things
-tmp_with_dots=`echo ${EXTRA_ROOT_QUALIFIERS} | sed 's/:/./g'`
-fq=${new_flavour}.${COMPILER_CODE}.${DEBUG_LEVEL}${tmp_with_dots}
+fq=${new_flavour}.${qualifiers_dots}
 topdir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}
-proddir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${PACKAGE_VERSION}
-verdir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${PACKAGE_VERSION}.version
-bindir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${PACKAGE_VERSION}/${fq}
-incdir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${PACKAGE_VERSION}/include
-upsdir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${PACKAGE_VERSION}/ups
+proddir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${UPS_STYLE_VERSION}
+verdir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${UPS_STYLE_VERSION}.version
+bindir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${UPS_STYLE_VERSION}/${fq}
+incdir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${UPS_STYLE_VERSION}/include
+upsdir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${UPS_STYLE_VERSION}/ups
 
 # I am not sure what this file is properly called.
 # I am calling it the fqfile, which is short for flavor qualifier file.
-tmp_with_underscore=`echo ${EXTRA_ROOT_QUALIFIERS} | sed 's/:/_/g'`
-fqfile=${verdir}/${old_flavour}_${COMPILER_CODE}_${DEBUG_LEVEL}${tmp_with_underscore}
+fqfile=${verdir}/${old_flavour}_${qualifiers_underscores}
 
 # Make directories, if needed.
 if ! [ -e ${topdir} ];then
@@ -107,17 +172,17 @@ rsync -ar --exclude-from  ${KINKAL_TO_UPS_DIR}/exclude_for_source.txt \
 cat > ${fqfile} <<EOF
 FILE = version
 PRODUCT = ${PACKAGE_NAME}
-VERSION = ${PACKAGE_VERSION}
+VERSION = ${UPS_STYLE_VERSION}
 
 #*************************************************
 #
 FLAVOR = ${old_flavour}
-QUALIFIERS = "${COMPILER_CODE}:${DEBUG_LEVEL}${EXTRA_ROOT_QUALIFIERS}"
+QUALIFIERS = "${qualifiers_colons}"
   DECLARER = `whoami`
   DECLARED = `date +"%Y-%m-%d %H:%M:%S GMT" -u`
   MODIFIER = `whoami`
   MODIFIED = `date +"%Y-%m-%d %H:%M:%S GMT" -u`
-  PROD_DIR = ${PACKAGE_NAME}/${PACKAGE_VERSION}
+  PROD_DIR = ${PACKAGE_NAME}/${UPS_STYLE_VERSION}
   UPS_DIR = ups
   TABLE_FILE = ${PACKAGE_NAME}.table
 
@@ -133,5 +198,3 @@ unset bindir
 unset incdir
 unset upsdir
 unset fqfile
-unset tmp_with_dots
-unset tmp_with_underscore
